### ISSUE TITLE
Solar radiation unit of measurement in 'lx' in stead of 'lux'

### ISSUE THREAD

**Issue by Calimerorulez** [dvandonkelaar/home-assistant-blueprints#3]
Hi

Thank you for creating this blueprint :)

I'm using it a couple of months now, and just added a light intensity sensor, which output 'lx' as unit of measurement. The sensor value sent to Weaher Underground isn't converted to W/m2. 

I saw in the following line:

https://github.com/dvandonkelaar/home-assistant-blueprints/blob/d7d72896f5b99a91df6602c96dadc21eb08c022f/wunderground_upload.yaml#L238C9-L238C9

that you have an if-statement that checks for the unit 'lux'. When I change the unit of measurement of my sensor to 'lux', trying to match your if-statement, Home Assistant throws the following error in the log:

`Entity sensor.bresser_lichtintentiteit (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'lux' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22`

Changing it back to 'lx' the error obviously goes away, but then the blueprint does not convert the value of my sensor anymore.

Can you fix it?

Bedankt en groeten,
Patrick

**Comment by dvandonkelaar** [comment]
Thanks for reporting the issue!
Can you check if the changed blueprint in the `wunderground/fix_lux` branch (commit c9f1afe) works?
Does this convert the value correctly or does this need some extra work?

**Comment by dvandonkelaar** [comment]
Closing due to no response.
